version: 0.2
phases: 
 install:
  runtime-versions:
   nodejs: 12

commands: 
- echo installing jest...
- npm install -g jest 
pre-build:
 commands: 
 - echo installing source npm dependencies...
 - npm install 
#  - npm install jest
#  - npm install axios
#  - npm install cheerio 
#  - npm install express

build: 
 commands: 
 - echo build started on `date`
 - echo Compiling the Node.js code
#  - jest sum.test.js 
 - npm build
 - npm test
post_build:
 commands:
 - echo Build completed on `date`

artifacts:
 files:
  - buildspec.yml
#   - sum.test.js
  - build/*

reports:
  jest_reports:
    files:
      - sum.test.js
    file-format: JUNITXML
    base-directory: premscraper



# version: 0.2
# phases: 
#  install:
#   runtime-versions:
#    nodejs: 12

# commands: 
# - echo installing jest...
# - npm install -g jest 
# pre-build:
#  commands: 
#  - echo installing source npm dependencies...
#  - npm install 
#  - npm install jest
#  - npm install axios
#  - npm install cheerio 
#  - npm install express

# build: 
#  commands: 
#  - echo build started on `date`
#  - echo Compiling the Node.js code
#  - jest sum.test.js 
# post_build:
#  commands:
#  - echo Build completed on `date`

# artifacts:
#  files:
#   - buildspec.yml
#   - build/*